# Generated by Codex on 2026-03-18

from django.db import migrations


def remove_unused_unknown_provider(apps, schema_editor):
    Provider = apps.get_model("billing", "Provider")
    (
        Provider.objects.filter(
            name="Unknown Provider",
            tax_id="UNKNOWN",
            barrels__isnull=True,
            invoices__isnull=True,
            users__isnull=True,
        )
        .distinct()
        .delete()
    )


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_invoice_provider"),
    ]

    operations = [
        migrations.RunPython(
            remove_unused_unknown_provider,
            migrations.RunPython.noop,
        ),
    ]
